# Generated by Django 5.0 on 2023-12-29 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichment", "0003_keyword_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="enrichment.category",
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="merchant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="enrichment.merchant",
            ),
        ),
    ]
