# Generated by Django 5.0 on 2023-12-30 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enrichment", "0004_keyword_category_alter_keyword_merchant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="type",
        ),
        migrations.DeleteModel(
            name="CategoryType",
        ),
    ]
