# Generated by Django 5.0 on 2023-12-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichment", "0005_remove_category_type_delete_categorytype"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.SmallIntegerField(
                choices=[(-1, "expense"), (1, "income")], default=-1
            ),
        ),
    ]
