# Generated by Django 5.0 on 2023-12-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichment", "0006_category_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="keyword",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("merchant__isnull", True), ("category__isnull", False)),
                    models.Q(("merchant__isnull", False), ("category__isnull", True)),
                    _connector="OR",
                ),
                name="check_either_merchant_or_category_and_only_one_is_null",
            ),
        ),
    ]
